hotfix: locked php-cs-fixer in version lower than 3.50 as new version causes errors in tests with current easy-coding-standards
1) Tests\CodingStandards\Unit\CsFixer\Phpdoc\MissingParamAnnotationsFixer\MissingParamAnnotationsFixerTest::testRegisteredFiles with data set #3 ('/var/www/html/packages/coding...d4.php', '/var/www/html/packages/coding...g4.php')
TypeError: PhpCsFixer\Tokenizer\Analyzer\Analysis\NamespaceUseAnalysis::__construct(): Argument #1 ($fullName) must be of type string, int given, called in /var/www/html/vendor/friendsofphp/php-cs-fixer/src/Tokenizer/Analyzer/NamespaceUsesAnalyzer.php on line 133

/var/www/html/vendor/symplify/easy-coding-standard/vendor/friendsofphp/php-cs-fixer/src/Tokenizer/Analyzer/Analysis/NamespaceUseAnalysis.php:54