fix yaml syntax. I caused error during deploy to kubernetes:
Error: Error reading document at index 0, yaml: line 48: found character that cannot start any token: yaml: line 48: found character that cannot start any token